# Generated by Django 4.2.2 on 2023-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
