# Generated by Django 4.2.2 on 2023-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_skill_personalinfo_experience_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='marital_status',
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
